### ISSUE TITLE
Окно с лицензией не закрывается при нажатии на Ок

### ISSUE THREAD

**Issue by Domerk** [Domerk/KcttDB#11]
Окно с лицензией не закрывается при нажатии на Ок. Ещё бы хорошо убрать оттуда ?, но установка WindowFlag в WindowSystemMenyHint делает кнопку закрытия окна (красный крестик) не активной.

**Comment by aizenbit** [comment]
Думаю, дело в том, что кнопка "Ок" не привязана к слоту close() твоего окна или как он там правильно называется. А для активации крестика можно попытаться добавить к WindowFlags ещё и WindowCloseButtonHint.

А почему бы не использовать QMessageBox? Если проблема в том, что нужна возможность копировать текст лицензии, [вот](http://stackoverflow.com/a/32591642) возможное решение.

**Comment by Domerk** [comment]
Ну, с кнопкой всё понятно, кроме того, что я постоянно про неё забываю хС
А лицензия пихается в текстэдит с параметром ReadOnly, потому что там автоскролл, и в целом мне нравится, как это выглядит.

Вот с флагами надо попробовать, спасибо ))

**Comment by aizenbit** [comment]
Кстааати. Автоскролл. Я тут как раз раздумываю, не сменить ли мне MIT на [Apache](http://licenseit.ru/wiki/index.php/Apache_License_version_2.0) или [Artistic](http://licenseit.ru/wiki/index.php/Artistic_License_2.0), а они длиннее MIT и потому скролл будет очень кстати.

**Comment by Domerk** [comment]
Мне даже MIT кажется слишком длинной для окна без скролла, честно говоря х)
А в QMessageBox не пихается лайаут. По крайней мере у меня не получилось это сделать. Потому и запихать туда какие-то дополнительные виджеты вряд ли возможно.

**Comment by aizenbit** [comment]
Хм. Я подумаю об этом)
Ну да, он такой, для узкого применения.

**Comment by Domerk** [comment]
Подумай ))

**Comment by aizenbit** [comment]
Кстати. Я помню, находил где-то, что в РФ текст лицензии обязательно должен быть на русском, но не помню, где именно, и сейчас снова не могу найти источник информации. Если вдруг наткнёшься на что-нибудь по этой теме, скинь мне, пожалуйста.

**Comment by Domerk** [comment]
Хм, ну чисто по логике лицензия - это официальный документ, а они все должны быть локализованы. Вроде как даже если у тебя есть какие-то зарубежные доки, для того, чтобы их таковыми считали, к ним должен прилагаться перевод (официальный или юридически заверенный). Но вообще да, надо погуглить.

**Comment by Domerk** [comment]
Проблема с внешним видом окон пофикшена, использованы флаги Qt::Window | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint

А с кнопочкой всё не так очевидно.

**Comment by Domerk** [comment]
Ладно, кнопочка тоже пофикшена ))

**Comment by aizenbit** [comment]
> Вроде как даже если у тебя есть какие-то зарубежные доки, для того, чтобы их таковыми считали, к ним должен прилагаться перевод (официальный или юридически заверенный). 

Да, но не совсем. По тому источнику, который я не могу найти, в РФ можно не переводить текст соглашения, если автор или распространитель программы за бугром. А вот если он в РФ - нужно всё писать по-русски. Мда, погуглю-ка я более тщательно.

**Comment by Domerk** [comment]
Погугли. Мне ничего по-быстрому нагуглить не удалось, но какая-то инфа на эту тему всё-таки должна быть.

_Риторический вопрос: почему нас всему этому не учили в универе?_

**Comment by aizenbit** [comment]
Вроде разобрался. [Вот тут](http://www.law4free.ru/consultations/objazatelen-li-dvujazychnyj-dogovor-s-inostrannym-postavshhikom-i-vozmozhna-li-oplata-v-dollarah.htm) чёрным по серому написано, что договор нужно обязательно составлять на русском языке, если хотя бы одна из заключающих договор сторон попадает под российские законы, например, является гражданином РФ или физически находится в РФ. Там идёт ссылка на третью статью 53-ФЗ "О государственном языке Российской федерации", где в пункте 1.1 написано:

> Государственный язык Российской Федерации подлежит обязательному использованию <...> в деятельности по ведению делопроизводства. 

Если мы заключаем лицензионный договор (а точнее, в нашем случае это не лицензионный договор, а договор присоединения), то мы ведём делопроизводство. Поэтому **перевод лицензии на русский нужно обязательно сделать**.

Дам ещё ссылки на конкретные статьи конкретных законов, которые подтверждают написанное в этом сообщении. Пусть будет, чтобы, если что, далеко не бегать.
- [ГК РФ Статья 428. Договор присоединения](http://www.consultant.ru/document/cons_doc_LAW_5142/9d688d8d974b72f3a0f35b2eee9605da4a2bddd0/)
- [ГК РФ Статья 1235. Лицензионный договор](http://www.consultant.ru/document/cons_doc_LAW_64629/640cbca01ece35bc535ffe5e6d96b7988d2daf6b/)
- [Федеральный закон 53-ФЗ "О государственном языке Российской Федерации" Статья 3. Сферы использования государственного языка Российской Федерации](http://www.consultant.ru/document/cons_doc_LAW_53749/4f8f696dc43e2fb3765d8c428d6a13139b5e2d62/#dst100020)
- [Закон РФ 1807-1 "О языках народов Российской Федерации" Статья 16. Использование языков в официальном делопроизводстве](http://www.consultant.ru/document/cons_doc_LAW_15524/8b948ff5a8560c4ded6c4c5ca9282fe88e78b5b2/)
- [Закон РФ 1807-1 "О языках народов Российской Федерации" Статья 22. Языки, используемые в сфере обслуживания и в коммерческой деятельности](http://www.consultant.ru/document/cons_doc_LAW_15524/af91dc567982d5229369ccce0f0d626524e9b529/)

**Comment by aizenbit** [comment]
Поискал заодно инфу насчёт Apache License 2.0. Для начала, я не написал, нафига она нужна, если есть MIT. Дело в том, что она лучше защищает разработчика от троллей и прочих нехороших людей. По крайней мере, [так считает FSF](https://www.gnu.org/licenses/license-list.html#apache2), но лично я с ними тоже согласен. В связи с тем, что написано комментарием выше, я посмотрел, что там с переводами этой лицензиии. В сети есть [два](http://licenseit.ru/wiki/index.php/Apache_License_version_2.0) [перевода](http://www.dataved.ru/2011/03/apache-license-2.html), но:
- Они оба сделаны, похоже, не юристами. Даже мне бросаются в глаза термины, не принятые в русском юридическом. Поэтому мне не очень понятно, чего там с юридической силой этих переводов.
- Надо будет в каждый файл добавлять инфу о лицензии, а это не очень-то удобно. 
- Если ты изменишь чей-то файл, надо будет в разделе лицензии дописать, что именно ты изменил, и это довольно стрёмно при коллективной разработке.

В общем, пока что я остаюсь на MIT. И, ух ты, я теперь могу обосновать это чем-то отличным от "ну она такая короткая и понятная". :laughing:

**Comment by Domerk** [comment]
Спасибо))
