### ISSUE TITLE
Дерево напрвленностей не обновляется

### ISSUE THREAD

**Issue by aizenbit** [Domerk/KcttDB#34]
Если создать новую направленность, а в ней - новое объединение, объединение не будет отображаться в дереве направленностей до тех пор, пока приложение не будет перезапущено.

**Comment by Domerk** [comment]
В отладочной версии этого бага нет. Нужны дополнительные тесты.

**Comment by Domerk** [comment]
В сборке есть: при добавлении направленности дерево обновляется, при добавлении объединения в новую направленность - нет.

**Comment by Domerk** [comment]
При этом это происходит только если просматривать и добавлять объединения через вторую половину дерева. Через "Общее" такой проблемы нет.

**Comment by Domerk** [comment]
Пофикшено.
