### ISSUE TITLE
Есть возможность редактирования некоторых "ридонли" таблиц

### ISSUE THREAD

**Issue by aizenbit** [Domerk/KcttDB#35]
При выборе направленностей, объединений и т.п. по кнопке рядом с нередактируемым полем (например, при добавлении новых объединения или группы) можно редактировать содержимое появляющейся таблицы, и отредактированное значение отображается в поле добавления. При этом по нажатию "Сохранить" в базу всё равно записывается корректное (существующее в базе данных) значение поля.

**Comment by Domerk** [comment]
Запретить редактирование вспомогательных таблиц?

**Comment by aizenbit** [comment]
Да. 

Ещё, например, можно редактировать список групп при изменении объединения, хотя это ни на что не влияет.

**Comment by Domerk** [comment]
В общем, гляну и постараюсь пофиксить.

**Comment by Domerk** [comment]
Редактирование вспомогательных таблиц запрещено.

**Comment by Domerk** [comment]
Редактирование таблиц в формах тоже запрещено.
В общем, всё пофикшено.
