### ISSUE TITLE
Проблемы с годом обучения в группе

### ISSUE THREAD

**Issue by aizenbit** [Domerk/KcttDB#36]
- [x]  Год обучения в бд всегда равен 0, даже если при добавлении/изменении был указан другой год
- [x]  При добавлении/изменении год обучения двузначный, в расширенном поиске - однозначный, в простом поиске ограничений нет вообще

**Comment by Domerk** [comment]
Первое надо тестить дополнительно - на другом компе у меня этого бага нет:

![default](https://cloud.githubusercontent.com/assets/6494262/20458305/43d27cb0-aeb2-11e6-8166-ec7eaf98decc.PNG)

**Comment by Domerk** [comment]
Второе пофикшено.

**Comment by aizenbit** [comment]
С первым для начала предлагаю определить место возникновения бага. Попробуй перенести удодов с одного компа на другой (не только ехешники, а целиком папку с программой и настройками), может быть проблема в конкретной версии удода. Например, из-за того, что неудачно скомпилировалась. Если нет, тогда придётся тестить.

**Comment by Domerk** [comment]
Так, происходит вот что:
- При создании группы ей можно указать любой допустимый год обучения и всё будет ок;
- При изменении группы новый год обучения не сохраняется.

То есть баг где-то в редактировании записи.

**Comment by Domerk** [comment]
Запись о группе не обновляется, если там пустой преподаватель - дело в ссылочной целостности и превращении null в 0.

**Comment by Domerk** [comment]
Решено.
Теперь нужно проверять, не добавились ли в процессе решения новые баги.
