### ISSUE TITLE
Пофиксить

### ISSUE THREAD

**Issue by Domerk** [Domerk/KcttDB#4]
- [x] Проблемы с буквой ё у регулярных выражений.
- [x] Ширина элементов MainWindow при запуске программы.
- [x] Изменить ввод дат (разбить дату на день - месяц - год, как в проге для временной базы)
- [x] Триггеры на удаление. Функция, формирующая запрос на удаление, использует имя таблицы / представления. Для представлений создать триггеры, которые будут удалять инфу из соответствующих таблиц.
- [x] Не работает фича с группой "Без группы", куда должны попадать дети из базы с самозаписью.
  Фича заработала, но надо дописать удаление из "Без группы" при добавлении в группу.
- [x] Во вспомогательных табличках перестал отображаться тулбар поиска.

Баги:
- [x] После вызова окна со вспомогательной таблицей при попытке перехода на другую основную таблицу (выбор элемента дерева) всё ложится.
- [x] При выделении ячейки в пустой строке в таблицах Объединения и Группы всё ложится.

**Comment by Domerk** [comment]
- [x] Разобраться с багом, из-за которого при сортировке (и мб не только) перестаёт отображаться содержимое некоторых ячеек.

**Comment by Domerk** [comment]
Возможно:
- [ ] Сделать поиск регистронезависимым.

На данный момент поиск регистрозависем, и пофиксить это средствами SQLite никак нельзя.

**Comment by aksenoff** [comment]
https://habrahabr.ru/post/150543/

**Comment by Domerk** [comment]
Хм. Хм. Сложна. Вообще, мне кажется, городить нечто будет смысл только в том случае, если мы решим, что будет использовать какую-то конкретную СУБД и только её. Я честно попыталась добавить регистронезависимость, модифицируя поисковый запрос (речь идёт о пользовательском поиске - он базируется на Like), то есть не городя лишнего в коде, но как-то ничего не вышло.

Ну и, конечно, это недостаток проги, но устранять его логично будет уже тогда, когда будет дописан остальной функционал: сейчас я работаю над конструированием запросов для расширенного поиска и созданием связей между таблицами.

**Comment by aksenoff** [comment]
Проблема в том, что если в роли СУБД будет SQLite, LIKE не будет работать как надо, так как в ядро SQLite не встроены необходимые collation'ы.
С другими СУБД проблем наблюдаться не должно.

Алсо https://habrahabr.ru/post/57915/

**Comment by Domerk** [comment]
Я думаю, что в итоге SQLite таки заменится на какой-нибудь MySQL, так как нам в итоге понадобятся человеческие транзакции для базы с самозаписью. Ну и нормальный Like, судя по всему, тоже.
В коде для этого нужно будет поменять от силы пару строчек, и всё упирается в то, что у меня так и не получилось понять, что там надо делать с драйвером. Но эти проблемы, мне кажется, решаемы.
